# Generated by Django 4.2.20 on 2025-04-17 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_rename_result_startupidea_business_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupidea',
            name='public_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
