# Generated by Django 4.2.20 on 2025-04-17 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_alter_startupidea_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupidea',
            name='original_idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='ideas.startupidea'),
        ),
    ]
